###

POST https://dummyjson.com/products/add
Content-Type: application/json

{
  "id": 101,
  "title": "Pumpkin",
  "price": "3.56"
}

###
http://localhost:3000

###
http://localhost:3000/api/v1/products

###
POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
    "id": 101,
    "title": "Pumpkin",
    "price": "3.56"
}

###
PATCH http://localhost:3000/api/v1/products/31

Content-Type: application/json
{
    "title": "Pumpkin Spice Latte",
    "price": "6.56"
}

###
DELETE http://localhost:3000/api/v1/products/31


/////////////////////// USERS /////////////////////////

###
http://localhost:3000/api/v1/users

###
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "firstName": "Olamide",
    "lastName": "Kumapayi",
    "email": "olamide@kumapayi.com",
    "password": "password"
}

###
PATCH http://localhost:3000/api/v1/users/31
Content-Type: application/json

{
  "firstName": "Paul"
}

###
DELETE http://localhost:3000/api/v1/users/31

###
POST http://localhost:3000/api/v1/users/register
Content-Type: application/json

{
    "firstName": "Olamide",
    "lastName": "Kumapayi",
    "email": "olamide@kumapayi.com",
    "password": "password"
}

###
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
  "email": "olamide@kumapayi.com",
  "password": "password"
}
